### ISSUE TITLE
Ajouter Redux devtools

### ISSUE THREAD

**Issue by charlyx** [frinyvonnick/nantesjs#42]
https://github.com/zalmoxisus/redux-devtools-extension

**Comment by frinyvonnick** [comment]
Il faut voir ça avec k-simple-state. Je crois que c'est le cas sur le master mais pas dans la version publish sur npm 😢

**Comment by frinyvonnick** [comment]
Après vérification il suffit de passer en version 0.4.0 👍

**Comment by charlyx** [comment]
C'est activé par défaut avec k-ramel <3
